### PR TITLE
first time to reproduce build.R

### PR DESCRIPTION
**Pull request by wangzhao0217**

### CODE REVIEW

**Comment by wangzhao0217** [comment]
Hi Robin,
 To get the code tun, I did the following changes: 
Can you confirm the setting of min_grouped_length ?
```{r}
r_key_network_igroups = r_key_network_igroups %>%
  mutate(length = st_length(geometry))
min_grouped_length = 1000 
```
https://github.com/nptscot/coherentnet/blob/f131feefd05391615b2ad1fdafb60a09b5852df6/README.qmd#L192C1-L194C27

Can you confirm the setting of the column match?
```{r}
r_high_g_not_ref = r_high_g_not_ref %>% select(names(r_key_roads_near))
```
https://github.com/nptscot/coherentnet/blob/f131feefd05391615b2ad1fdafb60a09b5852df6/README.qmd#L222C1-L223C34

**Comment by Robinlovelace** [comment]
> Can you confirm the setting of min_grouped_length ?
> 
> ```
> r_key_network_igroups = r_key_network_igroups %>%
>   mutate(length = st_length(geometry))
> min_grouped_length = 1000 
> ```

That sounds about right, there's no objective right answer for it.

**Comment by Robinlovelace** [comment]
We need to add number of lanes to it. We can get that from OSM data.

**Review by Robinlovelace — COMMENTED** [review]
Taking a look at this now Zhao.

**Comment by Robinlovelace** [comment]
Currently the code does not run. Can you upload the `"rj_joined_QGIS.geojson"` file @wangzhao0217 ?

**Review by Robinlovelace — APPROVED** [review]

**Pull request merged**
